[package]
name = "rodio"
version = "0.6.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/tomaka/rodio"
documentation = "http://docs.rs/rodio"

[dependencies]
claxon = { version = "0.3.0", optional = true }
cpal = "0.6.0"
hound = { version = "1.0.0", optional = true }
lazy_static = "1.0.0"
lewton = { version = "0.5", optional = true }
cgmath = "0.16"

[features]
default = ["flac", "vorbis", "wav"]

flac = ["claxon"]
vorbis = ["lewton"]
wav = ["hound"]
